server:
    port : 8080
spring:
    datasource:
        username: root
        password: password
        url: jdbc:mysql://localhost:3306/coin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
