spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/coin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: @profiles.active@
  security:
    user:
      name: wuminxuan
      password: 123456
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.codemonkeys.backendcoin.entity